using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Orthanc.CSharp.PluginsCore.Enums
{
    public enum OrthancPluginErrorCode
    {
        OrthancPluginErrorCode_InternalError = -1    /*!< Internal error */,
        OrthancPluginErrorCode_Success = 0    /*!< Success */,
        OrthancPluginErrorCode_Plugin = 1    /*!< Error encountered within the plugin engine */,
        OrthancPluginErrorCode_NotImplemented = 2    /*!< Not implemented yet */,
        OrthancPluginErrorCode_ParameterOutOfRange = 3    /*!< Parameter out of range */,
        OrthancPluginErrorCode_NotEnoughMemory = 4    /*!< Not enough memory */,
        OrthancPluginErrorCode_BadParameterType = 5    /*!< Bad type for a parameter */,
        OrthancPluginErrorCode_BadSequenceOfCalls = 6    /*!< Bad sequence of calls */,
        OrthancPluginErrorCode_InexistentItem = 7    /*!< Accessing an inexistent item */,
        OrthancPluginErrorCode_BadRequest = 8    /*!< Bad request */,
        OrthancPluginErrorCode_NetworkProtocol = 9    /*!< Error in the network protocol */,
        OrthancPluginErrorCode_SystemCommand = 10    /*!< Error while calling a system command */,
        OrthancPluginErrorCode_Database = 11    /*!< Error with the database engine */,
        OrthancPluginErrorCode_UriSyntax = 12    /*!< Badly formatted URI */,
        OrthancPluginErrorCode_InexistentFile = 13    /*!< Inexistent file */,
        OrthancPluginErrorCode_CannotWriteFile = 14    /*!< Cannot write to file */,
        OrthancPluginErrorCode_BadFileFormat = 15    /*!< Bad file format */,
        OrthancPluginErrorCode_Timeout = 16    /*!< Timeout */,
        OrthancPluginErrorCode_UnknownResource = 17    /*!< Unknown resource */,
        OrthancPluginErrorCode_IncompatibleDatabaseVersion = 18    /*!< Incompatible version of the database */,
        OrthancPluginErrorCode_FullStorage = 19    /*!< The file storage is full */,
        OrthancPluginErrorCode_CorruptedFile = 20    /*!< Corrupted file (e.g. inconsistent MD5 hash) */,
        OrthancPluginErrorCode_InexistentTag = 21    /*!< Inexistent tag */,
        OrthancPluginErrorCode_ReadOnly = 22    /*!< Cannot modify a read-only data structure */,
        OrthancPluginErrorCode_IncompatibleImageFormat = 23    /*!< Incompatible format of the images */,
        OrthancPluginErrorCode_IncompatibleImageSize = 24    /*!< Incompatible size of the images */,
        OrthancPluginErrorCode_SharedLibrary = 25    /*!< Error while using a shared library (plugin) */,
        OrthancPluginErrorCode_UnknownPluginService = 26    /*!< Plugin invoking an unknown service */,
        OrthancPluginErrorCode_UnknownDicomTag = 27    /*!< Unknown DICOM tag */,
        OrthancPluginErrorCode_BadJson = 28    /*!< Cannot parse a JSON document */,
        OrthancPluginErrorCode_Unauthorized = 29    /*!< Bad credentials were provided to an HTTP request */,
        OrthancPluginErrorCode_BadFont = 30    /*!< Badly formatted font file */,
        OrthancPluginErrorCode_DatabasePlugin = 31    /*!< The plugin implementing a custom database back-end does not fulfill the proper interface */,
        OrthancPluginErrorCode_StorageAreaPlugin = 32    /*!< Error in the plugin implementing a custom storage area */,
        OrthancPluginErrorCode_EmptyRequest = 33    /*!< The request is empty */,
        OrthancPluginErrorCode_NotAcceptable = 34    /*!< Cannot send a response which is acceptable according to the Accept HTTP header */,
        OrthancPluginErrorCode_SQLiteNotOpened = 1000    /*!< SQLite: The database is not opened */,
        OrthancPluginErrorCode_SQLiteAlreadyOpened = 1001    /*!< SQLite: Connection is already open */,
        OrthancPluginErrorCode_SQLiteCannotOpen = 1002    /*!< SQLite: Unable to open the database */,
        OrthancPluginErrorCode_SQLiteStatementAlreadyUsed = 1003    /*!< SQLite: This cached statement is already being referred to */,
        OrthancPluginErrorCode_SQLiteExecute = 1004    /*!< SQLite: Cannot execute a command */,
        OrthancPluginErrorCode_SQLiteRollbackWithoutTransaction = 1005    /*!< SQLite: Rolling back a nonexistent transaction (have you called Begin()?) */,
        OrthancPluginErrorCode_SQLiteCommitWithoutTransaction = 1006    /*!< SQLite: Committing a nonexistent transaction */,
        OrthancPluginErrorCode_SQLiteRegisterFunction = 1007    /*!< SQLite: Unable to register a function */,
        OrthancPluginErrorCode_SQLiteFlush = 1008    /*!< SQLite: Unable to flush the database */,
        OrthancPluginErrorCode_SQLiteCannotRun = 1009    /*!< SQLite: Cannot run a cached statement */,
        OrthancPluginErrorCode_SQLiteCannotStep = 1010    /*!< SQLite: Cannot step over a cached statement */,
        OrthancPluginErrorCode_SQLiteBindOutOfRange = 1011    /*!< SQLite: Bing a value while out of range (serious error) */,
        OrthancPluginErrorCode_SQLitePrepareStatement = 1012    /*!< SQLite: Cannot prepare a cached statement */,
        OrthancPluginErrorCode_SQLiteTransactionAlreadyStarted = 1013    /*!< SQLite: Beginning the same transaction twice */,
        OrthancPluginErrorCode_SQLiteTransactionCommit = 1014    /*!< SQLite: Failure when committing the transaction */,
        OrthancPluginErrorCode_SQLiteTransactionBegin = 1015    /*!< SQLite: Cannot start a transaction */,
        OrthancPluginErrorCode_DirectoryOverFile = 2000    /*!< The directory to be created is already occupied by a regular file */,
        OrthancPluginErrorCode_FileStorageCannotWrite = 2001    /*!< Unable to create a subdirectory or a file in the file storage */,
        OrthancPluginErrorCode_DirectoryExpected = 2002    /*!< The specified path does not point to a directory */,
        OrthancPluginErrorCode_HttpPortInUse = 2003    /*!< The TCP port of the HTTP server is already in use */,
        OrthancPluginErrorCode_DicomPortInUse = 2004    /*!< The TCP port of the DICOM server is already in use */,
        OrthancPluginErrorCode_BadHttpStatusInRest = 2005    /*!< This HTTP status is not allowed in a REST API */,
        OrthancPluginErrorCode_RegularFileExpected = 2006    /*!< The specified path does not point to a regular file */,
        OrthancPluginErrorCode_PathToExecutable = 2007    /*!< Unable to get the path to the executable */,
        OrthancPluginErrorCode_MakeDirectory = 2008    /*!< Cannot create a directory */,
        OrthancPluginErrorCode_BadApplicationEntityTitle = 2009    /*!< An application entity title (AET) cannot be empty or be longer than 16 characters */,
        OrthancPluginErrorCode_NoCFindHandler = 2010    /*!< No request handler factory for DICOM C-FIND SCP */,
        OrthancPluginErrorCode_NoCMoveHandler = 2011    /*!< No request handler factory for DICOM C-MOVE SCP */,
        OrthancPluginErrorCode_NoCStoreHandler = 2012    /*!< No request handler factory for DICOM C-STORE SCP */,
        OrthancPluginErrorCode_NoApplicationEntityFilter = 2013    /*!< No application entity filter */,
        OrthancPluginErrorCode_NoSopClassOrInstance = 2014    /*!< DicomUserConnection: Unable to find the SOP class and instance */,
        OrthancPluginErrorCode_NoPresentationContext = 2015    /*!< DicomUserConnection: No acceptable presentation context for modality */,
        OrthancPluginErrorCode_DicomFindUnavailable = 2016    /*!< DicomUserConnection: The C-FIND command is not supported by the remote SCP */,
        OrthancPluginErrorCode_DicomMoveUnavailable = 2017    /*!< DicomUserConnection: The C-MOVE command is not supported by the remote SCP */,
        OrthancPluginErrorCode_CannotStoreInstance = 2018    /*!< Cannot store an instance */,
        OrthancPluginErrorCode_CreateDicomNotString = 2019    /*!< Only string values are supported when creating DICOM instances */,
        OrthancPluginErrorCode_CreateDicomOverrideTag = 2020    /*!< Trying to override a value inherited from a parent module */,
        OrthancPluginErrorCode_CreateDicomUseContent = 2021    /*!< Use \"Content\" to inject an image into a new DICOM instance */,
        OrthancPluginErrorCode_CreateDicomNoPayload = 2022    /*!< No payload is present for one instance in the series */,
        OrthancPluginErrorCode_CreateDicomUseDataUriScheme = 2023    /*!< The payload of the DICOM instance must be specified according to Data URI scheme */,
        OrthancPluginErrorCode_CreateDicomBadParent = 2024    /*!< Trying to attach a new DICOM instance to an inexistent resource */,
        OrthancPluginErrorCode_CreateDicomParentIsInstance = 2025    /*!< Trying to attach a new DICOM instance to an instance (must be a series, study or patient) */,
        OrthancPluginErrorCode_CreateDicomParentEncoding = 2026    /*!< Unable to get the encoding of the parent resource */,
        OrthancPluginErrorCode_UnknownModality = 2027    /*!< Unknown modality */,
        OrthancPluginErrorCode_BadJobOrdering = 2028    /*!< Bad ordering of filters in a job */,
        OrthancPluginErrorCode_JsonToLuaTable = 2029    /*!< Cannot convert the given JSON object to a Lua table */,
        OrthancPluginErrorCode_CannotCreateLua = 2030    /*!< Cannot create the Lua context */,
        OrthancPluginErrorCode_CannotExecuteLua = 2031    /*!< Cannot execute a Lua command */,
        OrthancPluginErrorCode_LuaAlreadyExecuted = 2032    /*!< Arguments cannot be pushed after the Lua function is executed */,
        OrthancPluginErrorCode_LuaBadOutput = 2033    /*!< The Lua function does not give the expected number of outputs */,
        OrthancPluginErrorCode_NotLuaPredicate = 2034    /*!< The Lua function is not a predicate (only true/false outputs allowed) */,
        OrthancPluginErrorCode_LuaReturnsNoString = 2035    /*!< The Lua function does not return a string */,
        OrthancPluginErrorCode_StorageAreaAlreadyRegistered = 2036    /*!< Another plugin has already registered a custom storage area */,
        OrthancPluginErrorCode_DatabaseBackendAlreadyRegistered = 2037    /*!< Another plugin has already registered a custom database back-end */,
        OrthancPluginErrorCode_DatabaseNotInitialized = 2038    /*!< Plugin trying to call the database during its initialization */,
        OrthancPluginErrorCode_SslDisabled = 2039    /*!< Orthanc has been built without SSL support */,
        OrthancPluginErrorCode_CannotOrderSlices = 2040    /*!< Unable to order the slices of the series */,
        OrthancPluginErrorCode_NoWorklistHandler = 2041    /*!< No request handler factory for DICOM C-Find Modality SCP */,

        _OrthancPluginErrorCode_INTERNAL = 0x7fffffff
    }
}
